name: branvier_lints
description: Lints used in Branvier projects.
version: 0.2.2
homepage: https://github.com/branvier-dev/branvier_lints
topics: [branvier, lints, linter, analysis, analyzer]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  custom_lint_builder: ^0.6.2
  pyramid_lint: ^1.5.0
  solid_lints: ^0.1.4